### ISSUE TITLE
PCRE 2.8 leak

### ISSUE THREAD

**Issue by ben51degrees** [51Degrees/device-detection-nginx#25]
When running memory leak tests, a leak is detected from the PCRE 2.8 library.

This is from an allocation for a RegEx when an `if` statement is present in the config file.

As it is not from this module, detection of leaks from the PCRE library have been suppressed. See [suppressions.txt](https://github.com/51Degrees/device-detection-nginx/blob/main/suppressions.txt). If this is fixed, the suppression can be removed.

Stack trace from the leak:
```
Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fa05bf73867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5589bb29ee17 in ngx_alloc src/os/unix/ngx_alloc.c:22
    #2 0x5589bb2bf635 in ngx_regex_malloc src/core/ngx_regex.c:508
    #3 0x7fa05bd485d2  (/lib/x86_64-linux-gnu/libpcre2-8.so.0+0x115d2)
    #4 0x5589bb329dff in ngx_http_regex_compile src/http/ngx_http_variables.c:2553
    #5 0x5589bb3f1683 in ngx_http_rewrite_if_condition src/http/modules/ngx_http_rewrite_module.c:768
    #6 0x5589bb3f00a5 in ngx_http_rewrite_if src/http/modules/ngx_http_rewrite_module.c:589
    #7 0x5589bb253820 in ngx_conf_handler src/core/ngx_conf_file.c:463
    #8 0x5589bb252831 in ngx_conf_parse src/core/ngx_conf_file.c:319
    #9 0x5589bb2dd53d in ngx_http_core_location src/http/ngx_http_core_module.c:3224
    #10 0x5589bb253820 in ngx_conf_handler src/core/ngx_conf_file.c:463
    #11 0x5589bb252831 in ngx_conf_parse src/core/ngx_conf_file.c:319
    #12 0x5589bb2db6b1 in ngx_http_core_server src/http/ngx_http_core_module.c:2981
    #13 0x5589bb253820 in ngx_conf_handler src/core/ngx_conf_file.c:463
    #14 0x5589bb252831 in ngx_conf_parse src/core/ngx_conf_file.c:319
    #15 0x5589bb2c0f9a in ngx_http_block src/http/ngx_http.c:239
    #16 0x5589bb253820 in ngx_conf_handler src/core/ngx_conf_file.c:463
    #17 0x5589bb252831 in ngx_conf_parse src/core/ngx_conf_file.c:319
    #18 0x5589bb248110 in ngx_init_cycle src/core/ngx_cycle.c:284
    #19 0x5589bb1f4e21 in main src/core/nginx.c:292
    #20 0x7fa05bb1ad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
```

**Comment by ben51degrees** [comment]
Closed with 6fb6f0af554912defbf743d1f50228f3e6e69c4a
